baseurl: "/wncc" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-sitemap

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

domain: wncc-soc.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://wncc.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /_site/
